/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProjectIdRouteImport } from './routes/$projectId'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DeploymentDeploymentIdRouteImport } from './routes/deployment.$deploymentId'

const ProjectIdRoute = ProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DeploymentDeploymentIdRoute = DeploymentDeploymentIdRouteImport.update({
  id: '/deployment/$deploymentId',
  path: '/deployment/$deploymentId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$projectId': typeof ProjectIdRoute
  '/deployment/$deploymentId': typeof DeploymentDeploymentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$projectId': typeof ProjectIdRoute
  '/deployment/$deploymentId': typeof DeploymentDeploymentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$projectId': typeof ProjectIdRoute
  '/deployment/$deploymentId': typeof DeploymentDeploymentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$projectId' | '/deployment/$deploymentId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$projectId' | '/deployment/$deploymentId'
  id: '__root__' | '/' | '/$projectId' | '/deployment/$deploymentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProjectIdRoute: typeof ProjectIdRoute
  DeploymentDeploymentIdRoute: typeof DeploymentDeploymentIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$projectId': {
      id: '/$projectId'
      path: '/$projectId'
      fullPath: '/$projectId'
      preLoaderRoute: typeof ProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deployment/$deploymentId': {
      id: '/deployment/$deploymentId'
      path: '/deployment/$deploymentId'
      fullPath: '/deployment/$deploymentId'
      preLoaderRoute: typeof DeploymentDeploymentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProjectIdRoute: ProjectIdRoute,
  DeploymentDeploymentIdRoute: DeploymentDeploymentIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
